server:
  port: 8081

test:
  url:
    http://test:8080
    
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
   fetchRegistry: true
    
#ribbon
ribbon:
  eureka:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb+srv://mkpuser:mkpuser@mkp-cr-marketplace-core-dev-lcr88.gcp.mongodb.net/test?retryWrites=true&w=majority
      database: db-market-place-core